### ISSUE TITLE
Add fullpage caching

### ISSUE THREAD

**Issue by Putr** [Pirate-Parties-International/PPI-rest-api#29]
Find/create a very simple favicon for the page (Pirate logo or some hint at the name etc.) and add it to the repo (note: this only requires you add a file and a line of html in the base file)

**Comment by Putr** [comment]
@j-h-s This is probably the simplest task for you to start with. Don't worry to much about how the favicon looks, it can just be a white P in a square blue box.

**Comment by j-h-s** [comment]
@Putr I added the favicon to /web/img because when I tried leaving it in /web the symfony logo kept overriding it. But I also replaced the ones in /web, just in case.

**Comment by Putr** [comment]
:+1:
