### ISSUE TITLE
Add link to PPEU and PPI

### ISSUE THREAD

**Issue by collentine** [Pirate-Parties-International/PPI-rest-api#30]
At the party pages one of the boxes display memberships. e.g. http://api.piratetimes.net/party/ppde

Please adjust the code to provide a clickable link to PPI and PPEU websites.

http://www.pp-international.net/
http://europeanpirateparty.eu/

**Comment by PeterTheOne** [comment]
I made some changes.. but I'm not sure if they actually work ^^°
