### ISSUE TITLE
deploy updated webpage

### ISSUE THREAD

**Issue by collentine** [Pirate-Parties-International/PPI-rest-api#33]
several changes have been done to the API and would be nice to have these displayed on website

**Comment by collentine** [comment]
ping @Putr

**Comment by collentine** [comment]
ping @Putr 

How can this step be made more efficient? Not good if website constantly lags behind data, sometimes with several weeks

**Comment by Putr** [comment]
Hmm, I'll think about if there is a smart way to do it.

Untill than - now that testing is automatized I only need 5 minutes to make a deploy (came online to do it after I saw some commits)

**Comment by Putr** [comment]
I'll update the data anytime there's a new version of the data (if I merge with merge requests). If @PeterTheOne or @collentine do any direct changes just add an issue here (or ping me on FB) and I'll run the commands to update the web.
