### ISSUE TITLE
Defunct status - import from dataset

### ISSUE THREAD

**Issue by Putr** [Pirate-Parties-International/PPI-rest-api#34]
A new switch has been added to the dataset: "defunct". It show if the party is no longer active.

The switch has already been imported to the dataset.

Task 2:
Display the datapoint on the party detail page (i.e. /party/[partyCode])

Note: Frontpage does not show any defunct parties, but they are still accessible via the url directly.

**Comment by j-h-s** [comment]
@Putr I added the "defunct" sign as a png so it can easily be replaced with something better looking later on.

**Comment by j-h-s** [comment]
Like I said, I thought that would be easier for someone to make it look better later, so the only had to replace the png, although I realise now that I forgot to add alt text anyway.
I can just make it a text layer, if you'd prefer.
