### ISSUE TITLE
Make use of jvectormap for front-page? [requires Jquery skills]

### ISSUE THREAD

**Issue by collentine** [Pirate-Parties-International/PPI-rest-api#35]
http://jvectormap.com/ enable a visual interactive map to be displayed. It can use JSON as source for data. Thus if we have anyone with Jquery skills we could integrate it with PAPI and create a nice-looking visual for our front-page. Hover over (or click) a country and info is displayed.

I tweaked an existing map but my coding skills are too basic to do much more http://test.collentine.com/world/ (inspiration)

**Comment by PeterTheOne** [comment]
Or use a leafletjs map just like in the party pages.
