### ISSUE TITLE
Add filter parameter to API

### ISSUE THREAD

**Issue by Putr** [Pirate-Parties-International/PPI-rest-api#4]
Add filtering to the /api/v1/parties/ endpoint.

This should filter by:
- member of PPI yes/no
- member of PPEU yes/no
- defunct yes/no
- country (pass country code, get parties from that country only)
- type
- region
- parentParty

Don't forget to add it to the /doc/api/v1 documentation (via annotations).

**Comment by PeterTheOne** [comment]
also add PPEU membership filter

**Comment by j-h-s** [comment]
@Putr Is that something like what you had in mind?

**Comment by j-h-s** [comment]
@Putr Never mind, I realised what you had in mind now.

**Comment by Putr** [comment]
Few notes:

1. Don't write long strings of If/elseif/else blocks, just use the switch()
2. Don't use "yes" and "no" magic strings. Use True/false.
3. As you can see the DB is set up in such a way that new international orgs can easily be added. Don't have a filter for each org. Have one that says "filter_by_org" and pass in a slug of that org to filter by.
4. You should not be filtering by membership in PHP, you should do it in DB. I know it's a tad more involved, but it is possible and it is the correct way.

Please see discussion on slack for more.

**Comment by j-h-s** [comment]
@Putr 
1. Okay, that's fine. I'll replace them.
2. "yes" and "no" are only there for user input, and the only piece of code that uses them is basically 'if the user wrote "yes" then set as true'. I tried defaulting them to true and false from the start, but the api view displayed them as 1 and 0, which I thought would be less clear.
3 & 4. That's also fine. I'll work on it.

**Comment by j-h-s** [comment]
The filters for country, region, type and parent party are currently obsolete, but I added their code as comments so they can be added quickly at a later date if/when they become more useful.

**Comment by Putr** [comment]
Regarding point 2:

Machines should always be operating with true/false, not magic strings. API is a machine readable format, with native "true/false" values that it understands and every decoder will correctly translate it to native boolean types.

Translation from boolean to human readable should be done in the template (it's writing 1/0 because you're just printing it out - you should have a simple IF statment in the twig template to pretty it up)

**Comment by Putr** [comment]
I cleanup the code a little - see my commit.

Note: The filters do not work correctly when more than one are selected. I eliminated a few bugs, but there are still a few more.
Note2: A new "IntOrg" has already been added - YPE.
