### ISSUE TITLE
Possible bug when importing data from FB, TW and Gplus

### ISSUE THREAD

**Issue by GuruVII** [Pirate-Parties-International/PPI-rest-api#40]
An example of the error, the FB data error is probably my fault. 

PPVenezuela - Exception: Invalid OAuth access token signature.     + ERROR while retrieving FB data
     + Starting Twitter import
     + ERROR while retrieving TW data
     + Starting GooglePlus import
     + Twitter data retrived
     + Statistic added
- Processing ypat
  - Starting Facebook import
    jupisat - Exception: Invalid OAuth access token signature.     + ERROR while retrieving FB data
  - Starting Twitter import
  - ERROR while retrieving TW data
- Processing ypcz
  - Starting Facebook import
  
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Fatal error: Call to a member function getField() on null 

https://dl.dropboxusercontent.com/u/7947412/Screenshot%20from%202016-07-13%2012-01-30.png

**Comment by j-h-s** [comment]
This happens when our link to a party's fb page is broken, as is the case with ypcz.
