### ISSUE TITLE
/api/v1/parties not returning data, but still giving a 200 OK response

### ISSUE THREAD

**Issue by GuruVII** [Pirate-Parties-International/PPI-rest-api#47]
Tested both in the sandbox and the page I'm currently working on.
Trying without any filters returns no data, but still gets a OK 200 response.
Interestingly enough it works, if the filter "show_defunct" is set, to either true or false, but that doesn't seem to change the data received)

**Comment by j-h-s** [comment]
Should be fixed now. This was from the old 'filter' branch that got overwritten by the latest 'scraper_mods' merge. It's my fault for letting that branch get so far behind the master.

**Comment by j-h-s** [comment]
Fixed by most recent deployment.
