### ISSUE TITLE
/api/v1/social/ returning post likes instead of social score

### ISSUE THREAD

**Issue by GuruVII** [Pirate-Parties-International/PPI-rest-api#49]
@Putr

**Comment by j-h-s** [comment]
What is 'social score'?

**Comment by GuruVII** [comment]
If anyone know it is @putr. I think I created this issue and just added putr's names only becuase he told me to do it.

**Comment by j-h-s** [comment]
Okay, after talking to @Putr about this, we need the following options.

- [ ] Total engagement (Likes + shares + comments, etc.)
- [ ] Likes compared to social reach (e.g. 'x% of followers liked this')
- [ ] Likes per capita (using data from somewhere like population.io)

Should be relatively easy stuff, but not particularly high-priority.

**Comment by j-h-s** [comment]
These options are now accessible from the api using 'fields=total_engagement,audience_reach,reach_per_capita'
