### ISSUE TITLE
Facebook statuses sometimes too long for db

### ISSUE THREAD

**Issue by j-h-s** [Pirate-Parties-International/PPI-rest-api#51]
Facebook supports statuses up to 63k characters. The DB only supports 255.

**Comment by j-h-s** [comment]
Worth noting that with utf8mb4 (#52), max string length is now only 191.

**Comment by Putr** [comment]
Why don't we just change our database to a TEXT field?

**Comment by j-h-s** [comment]
I thought about that, but I didn't know if that would greatly increase the server load. But if that's what you suggest, then I'll do it now.
