### ISSUE TITLE
Timeline for documentation

### ISSUE THREAD

**Issue by collentine** [Pirate-Parties-International/PPI-rest-api#6]
We're at the end of July and this project has been in development for +2 years. Do we have a timeline for when the documentation will be finished?

**Comment by Putr** [comment]
The documentation is at 80% (and is part of the INFO repo). I need, maybe, another hour. The API has been updated to Symfony2.7 and has had some major codecleanup done. See:
https://github.com/Pirate-Parties-International/PPI-rest-api/tree/rewrite

I had a meeting with the frontend dev that's working on this just 5 hours ago. He's a very green junior developer so it's gonna take him some time, but he is making great progress. Backend needs just some love and we're done.

Most of this will be compleated next week (I'm very, very swamped).

**Comment by PeterTheOne** [comment]
I'm looking forward to the documentation, thanks for your work. :)

**Comment by collentine** [comment]
time is passing. How close to finishing is the documentation and small parts on backend?

**Comment by collentine** [comment]
any progress? @Putr

**Comment by Putr** [comment]
Done
