### ISSUE TITLE
Handling missing info for posts/pictures

### ISSUE THREAD

**Issue by j-h-s** [Pirate-Parties-International/PPI-rest-api#60]
We need to disable the loading screen when there are no posts/pictures to display (for example - try selecting Pirate Party Leuven). Right now there's no way to navigate away from that page.

The problem with including defunct parties is that some of them will have nothing on social media.

@GuruVII

**Comment by GuruVII** [comment]
Fix one bug and another one is revealed :)
I'll fix it
